version: '3.8'

services:
  mqtt_broker:
    image: emqx/emqx:latest
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
      - "18083:18083"
    container_name: emqx
    networks:
      - simulations

  simulator:
    build:
      context: .
      dockerfile: simulator/Dockerfile
    volumes:
      - ./data:/app/data
    depends_on:
      - mqtt_broker
    environment:
      MQTT_BROKER_HOST: mqtt_broker
      MQTT_TOPIC: data
    container_name: simulator
    networks:
      - simulations

  telegraf:
    image: telegraf:1.30
    container_name: telegraf_sim
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mqtt_broker
    networks:
      - simulations
    command: ["sh", "-c", "sleep 20 && telegraf"]

  influxdb:
    image: influxdb:2.7
    container_name: influxdb_sim
    ports:
      - "8086:8086"
    volumes:
      - influxdb_simulation:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=gaudee
      - DOCKER_INFLUXDB_INIT_PASSWORD=mordor11
      - DOCKER_INFLUXDB_INIT_ORG=gaudee
      - DOCKER_INFLUXDB_INIT_BUCKET=linac7
      - DOCKER_INFLUXDB_ADMIN_TOKEN=PFf6gAxu1Cqju-6G7rZAG0oy8f6dyVlBwzpPPT-4SNp-nWg7Ofkc4NmKPdMgNG768JdRUZ4hOjyfpYJ9YPFVKQ==
    networks:
      - simulations
volumes:
  influxdb_simulation:

networks:
  simulations:
    driver: bridge