version: '3.8'

services:
  mqtt_broker:
    image: emqx/emqx:latest
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
      - "18083:18083"
    container_name: emqx
    networks:
      - simulations

  simulator:
    build:
      context: simulator
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    depends_on:
      - mqtt_broker
    environment:
      MQTT_BROKER_HOST: mqtt_broker
      MQTT_TOPIC: data
    container_name: simulator
    networks:
      - simulations
    command: ["sh", "-c", "sleep 20 && python simulator.py"]

  detection:
    build:
      context: detection
      dockerfile: Dockerfile
    depends_on:
      - influxdb
    environment:
      - INFLUX_URL=http://influxdb_sim:8086
      - INFLUX_TOKEN=87ghmfUTGX-V-YoJYbtWXluiAm4NPeekcmhnZnQg9v988tDsWnm6w25IvkEGORr2xcrDxFFPaHg57rYYwriVfQ==
      - ORGANIZATION=gaudee
      - BUCKET=linac7
    container_name: detection_sim
    networks:
      - simulations
    command: ["python", "-u", "detection.py"]

  telegraf:
    image: telegraf:1.30
    container_name: telegraf_sim
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - mqtt_broker
    networks:
      - simulations
    command: ["sh", "-c", "sleep 20 && telegraf"]

  influxdb:
    image: influxdb:2.7
    container_name: influxdb_sim
    ports:
      - "8086:8086"
    volumes:
      - influxdb_simulation:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=gaudee
      - DOCKER_INFLUXDB_INIT_PASSWORD=mordor11
      - DOCKER_INFLUXDB_INIT_ORG=gaudee
      - DOCKER_INFLUXDB_INIT_BUCKET=linac7
      - DOCKER_INFLUXDB_ADMIN_TOKEN=Uns235Eu7DAOhl3QJzlx2PC3RpUJLRcCbIfFbt2cuoyBfnSib55C86mwFmr_U6dKkSYpJgszZTR8KAOv1_4kfw==
    networks:
      - simulations
volumes:
  influxdb_simulation:

networks:
  simulations:
    driver: bridge