version: '3.8'

services:

  influxdb:
    image: influxdb:2.7
    container_name: influxdb_local
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=gaudee
      - DOCKER_INFLUXDB_INIT_PASSWORD=mordor11
      - DOCKER_INFLUXDB_INIT_ORG=gaudee
      - DOCKER_INFLUXDB_INIT_BUCKET=linac7
      - DOCKER_INFLUXDB_ADMIN_TOKEN=mordor111
    networks:
      - transitions

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      - transitions

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=gaudee
      - GF_SECURITY_ADMIN_PASSWORD=mordor11
    depends_on:
      - influxdb
    networks:
      - transitions
    
  detection:
    build: 
       context: .
       dockerfile: detection/Dockerfile
    container_name: detection
    depends_on:
      - influxdb
    environment:
      - INFLUX_URL=http://influxdb_local:8086
      - INFLUX_TOKEN=ftnNk75yqpo62jBsEWryKFNIq54Zu6_gB5LgYL7VD8ExGYhKIeE7LeEt_T2MMLS-WrkXfRx_zG3i3v1t7L62qw==
      - ORGANIZATION=gaudee
      - BUCKET=linac7
    networks:
      - transitions
  
  classification:
    build: 
       context: .
       dockerfile: classification/Dockerfile
    container_name: classification
    depends_on:
      - influxdb
    environment:
      - INFLUX_URL=http://influxdb_local:8086
      - INFLUX_TOKEN=ftnNk75yqpo62jBsEWryKFNIq54Zu6_gB5LgYL7VD8ExGYhKIeE7LeEt_T2MMLS-WrkXfRx_zG3i3v1t7L62qw==
      - ORGANIZATION=gaudee
      - BUCKET=linac7
    networks:
      - transitions

volumes:
  influxdb_data:
  grafana_data:

networks:
  transitions:
    driver: bridge